sudo: required
services:
  - docker

script:
  - docker build -t pulsardockerhub/react-example .
  - docker images pulsardockerhub/react-example

before_deploy:
  - docker login -u Pulsar -p dockerhub

deploy:
  provider: script
  script: docker push pulsardockerhub/react-example
  on:
    branch: master